repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v5.4.2'
    hooks:
    -   id: isort
        types: [file, python]
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        types: [file, python]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        additional_dependencies: [
            'flake8-comprehensions',
            'flake8-debugger',
            'flake8-eradicate',
            'flake8-mutable'
        ]
